on:
  push:
    branches: [3.14.2-fix]
  pull_request:
name: CI
jobs:
  flatpak:
    name: "Gamescope Vulkan Layer"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-23.08
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: org.freedesktop.Platform.VulkanLayer.gamescope.flatpak
        manifest-path: org.freedesktop.Platform.VulkanLayer.gamescope.yml
        cache-key: flatpak-builder-${{ github.sha }}
